### ISSUE TITLE
Error when specyfing subjects in ctStanDiscretePars

### ISSUE THREAD

**Issue by Kyabdro** [cdriveraus/ctsem#11]
I'm trying to plot specific subjects DRIFT matrix, however when specifying any integer in the `subjects `argument, this error is produced:

> Error in if ("all" %in% subjects || dim(e[[matname]])[2] == 1) { : 
>  missing value where TRUE / FALSE is required

I've noticed that the corresponding conditional part of the script is made to change the names of the object `e` from "DRIFT" to "pop_DRIFT" and so on:
  
```
for (matname in c("DRIFT", "DIFFUSIONcov", "asymDIFFUSION")) {
    if ("all" %in% subjects || dim(e[[matname]])[2] == 1) {
      ctpars[[matname]] <- e[[paste0("pop_", matname)]]
    }
```

I think this error is due to an uptade of `ctExtract `which does not give names such as "DRIFT" anymore but now directly give "pop_DIRFT", etc... I think the error might be resolved easily by modfying the script accordingly:

`for (matname in c("pop_DRIFT", "pop_DIFFUSIONcov", "pop_asymDIFFUSION"))`

Then deleting the first conditional part that is not usefull anymore.

Did I guessed rigth?

**Comment by cdriveraus** [comment]
You're right, it's a problem caused by some other changes, I'll try fix it or post a solution soon. The pop matrices represent the mean though, not the subject pars.

**Comment by Kyabdro** [comment]
Did you made some changes ?

FYI - I've tried to install the most recent version from the github repo, however I have this issue (using both functions mentionned in the package description) :

> installation of package ‘C:/Users/NPELLE~1/AppData/Local/Temp/RtmpiEtlOu/file4e802572663f/ctsem_3.3.12.tar.gz’ had non-zero exit status

I'm not shure if this is a problem from me or from the most recent version of the package...

**Comment by cdriveraus** [comment]
you caught me in the middle of a significant re-working sorry. hopefully another day and it's sorted. one of the recent commits had some errors, this should be fixed, but won't fix your issue.

**Comment by cdriveraus** [comment]
it still needs a little refining (certain cases are unnecessarily slow) but this feature is working properly again in the latest github release. You may need to re-fit any models, or you can try the ctStanFitUpdate() function.

**Comment by Kyabdro** [comment]
I've still the same problem with the package installation from github. Maybe I caught you again in a significant re-working =)

**Comment by cdriveraus** [comment]
Can you post the model and fit code? This element is more complex these days because of differences between the full sampling procedure and optimization, but for my tests it is working so I'm clearly missing something.

**Comment by Kyabdro** [comment]
Sorry I was not clear : my problem **is** the installtion of the package from github :

> installation of package ‘C:/Users/NPELLE~1/AppData/Local/Temp/RtmpiEtlOu/file4e802572663f/ctsem_3.3.12.tar.gz’ had non-zero exit status

**Comment by cdriveraus** [comment]
I see. Other machines have been building from that commit, but I pushed another update through in any case. Could you try again from a fresh R session -- either using the install script:
source(file = 'https://github.com/cdriveraus/ctsem/raw/master/installctsem.R')

or if you've already run it recently, just:
remotes::install_github('cdriveraus/ctsem', INSTALL_opts = "--no-multiarch", dependencies = c("Depends", "Imports"))

if there are still errors, please post the complete install output, it should show a more meaningful error somewhere.

**Comment by Kyabdro** [comment]
Not working again : 

> Downloading GitHub repo cdriveraus/ctsem@HEAD

> √  checking for file 'C:\Users\NPellerin\AppData\Local\Temp\Rtmp0Qvx52\remotes1c0c36dc3c24\cdriveraus-ctsem-85f3213/DESCRIPTION' (413ms)
> -  preparing 'ctsem': (2s)
> √  checking DESCRIPTION meta-information ... 
> -  cleaning src
> -  checking for LF line-endings in source and make files and shell scripts (1.2s)
> -  checking for empty or unneeded directories
> -  building 'ctsem_3.4.0.tar.gz'
>    
> Installing package into ‘C:/Users/NPellerin/OneDrive/Documents/R/win-library/4.0’
> (as ‘lib’ is unspecified)
> * installing *source* package 'ctsem' ...
> ** using staged installation
> ** libs
> "C:/PROGRA~1/R/R-40~1.2/bin/x64/Rscript" -e "source(file.path('..', 'tools', 'make_cc.R')); make_cc(commandArgs(TRUE))" stan_files/ctsmgen.stan
> "C:/PROGRA~1/R/R-40~1.2/bin/x64/Rscript" -e "source(file.path('..', 'tools', 'make_cc.R')); make_cc(commandArgs(TRUE))" stan_files/cov.stan
> "C:/PROGRA~1/R/R-40~1.2/bin/x64/Rscript" -e "source(file.path('..', 'tools', 'make_cc.R')); make_cc(commandArgs(TRUE))" stan_files/ctsm.stan
> 
> 
> DIAGNOSTIC(S) FROM PARSER:
> Info: integer division implicitly rounds to integer. Found int division: d * d - d / 2
>  Positive values rounded down, negative values rounded up or down in platform-dependent way.
> Info: integer division implicitly rounds to integer. Found int division: d * d - d / 2
>  Positive values rounded down, negative values rounded up or down in platform-dependent way.
> 
> Wrote C++ file "stan_files/cov.cc"
> "C:/rtools40/usr/bin/mingw64/bin/"g++ -m64 -std=c++1y -std=gnu++14 -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG -I"../inst/include" -I"C:/Users/NPellerin/OneDrive/Documents/R/win-library/4.0/StanHeaders/include/src" -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG -DRCPP_PARALLEL_USE_TBB=1 -I'C:/Users/NPellerin/OneDrive/Documents/R/win-library/4.0/BH/include' -I'C:/Users/NPellerin/OneDrive/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/NPellerin/OneDrive/Documents/R/win-library/4.0/RcppEigen/include' -I'C:/Users/NPellerin/OneDrive/Documents/R/win-library/4.0/RcppParallel/include' -I'C:/Users/NPellerin/OneDrive/Documents/R/win-library/4.0/rstan/include' -I'C:/Users/NPellerin/OneDrive/Documents/R/win-library/4.0/StanHeaders/include'      -DRCPP_PARALLEL_USE_TBB=1 -I"C:/Users/NPellerin/OneDrive/Documents/R/win-library/4.0/RcppParallel/include" -D_REENTRANT -DSTAN_THREADS     -mtune=native -O1 -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-ignored-attributes -Wno-deprecated-declarations -c init.cpp -o init.o
> sh: C:/rtools40/usr/bin/mingw64/bin/g++: No such file or directory
> make: *** [C:/PROGRA~1/R/R-40~1.2/etc/x64/Makeconf:229: init.o] Error 127
> make: *** Waiting for unfinished jobs....
> Wrote C++ file "stan_files/ctsmgen.cc"
> Wrote C++ file "stan_files/ctsm.cc"
> rm stan_files/ctsmgen.cc stan_files/ctsm.cc stan_files/cov.cc
> ERROR: compilation failed for package 'ctsem'
> * removing 'C:/Users/NPellerin/OneDrive/Documents/R/win-library/4.0/ctsem'
> * restoring previous 'C:/Users/NPellerin/OneDrive/Documents/R/win-library/4.0/ctsem'
> Warning message:
> In i.p(...) :
>   installation of package ‘C:/Users/NPELLE~1/AppData/Local/Temp/Rtmp0Qvx52/file1c0ca8c7f6a/ctsem_3.4.0.tar.gz’ had non-zero exit status

**Comment by cdriveraus** [comment]
Ok. You're on windows it looks like? rstan is not always so easy to get compiling, for some reason. There is some discussion about what I 'think' is the issue here: 
https://discourse.mc-stan.org/t/error-in-file-con-r-cannot-open-the-connection-c-rtools40-usr-mingw-bin-g-not-found/17310/2

The first thing to check seems to be the .Renviron file, which, if it exists, should be in your home directory. Make sure it doesn't have a BINPREF line, if it does, remove it.
https://stackoverflow.com/questions/40788645/how-to-create-renviron-file

**Comment by Kyabdro** [comment]
I don't have any BINPREF line, the only line present in .Renviron is

> PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"

Note that I had no trouble to install previous versions of ctsem, including the actual CRAN version. I'm not shure if this is an issue related to Rstan.

**Comment by Kyabdro** [comment]
Now, if I specify one subject with `ctStanDiscretePars` (e.g., `subjects = 4`) this work fine.

However specifying multiple subject (e.g., `subjects = c(2,4)`) does not work. I've tried to use `as.integer` to the vector of subjects but the same error occurs anyway :

> Error : $ operator is invalid for atomic vectors

**Comment by cdriveraus** [comment]
Sorry! that should be fixed too now. Here's the test script I was using, just in case of curiosity :) 

```
dri <- sort(-log1p(exp(rnorm(10,0,2))))

for(i in 1:10){
gm <- ctModel(LAMBDA=diag(1), DRIFT = dri[i],DIFFUSION = .1,MANIFESTVAR = .2,Tpoints=30,T0MEANS = 30)
d <- data.frame(ctGenerate(ctmodelobj = gm,n.subjects = 1,dtmean = .1),dri=dri[i])
d$id <- i
if(i==1) dat <- d else dat <- rbind(dat,d)
}
plot(dat$time,dat$Y1)

m <- ctModel(LAMBDA=diag(1),type='stanct',
  DRIFT = 'dr||||dri',
  TIpredNames = 'dri',tipredDefault = F)

f=ctStanFit(datalong = dat,ctstanmodel = m,plot=F,cores=1,
  savesubjectmatrices = T,verbose=1)



e=ctExtract(f,subjectMatrices = T,cores=6)
plot(e$subj_DRIFT[1,,,],dry)
e$subj_DRIFT[1,,,]
ctStanDiscretePars(ctstanfitobj = f,plot=T,subjects = 1)
ctStanDiscretePars(ctstanfitobj = f,plot=T,subjects = 10)
ctStanDiscretePars(ctstanfitobj = f,plot=T,subjects = c(1,10))
ctKalman(f,plot=T,subjects = 1:10,removeObs = T)

```

**Comment by Kyabdro** [comment]
Everything works fine now, thank you very much =)

**Comment by Kyabdro** [comment]
Ok, sorry, I reopened because I've a different problem still related to this function. 

I'm trying to plot on the same graph the same parameter for two different groups. When I try to use `add=T` with the second group a new plot is created.

Here is an exemple based on your script above

```
ctStanDiscretePars(ctstanfitobj = f,plot=T,subjects = 1:5)
ctStanDiscretePars(ctstanfitobj = f,plot=T,subjects = 6:10,add=T) # new plot, not drawing in the same plot
```

Also I noticed the following error if `times` is specified in `ctStanDiscretePars `and not in `ctStanDiscreteParsPlot`.

```
x=ctStanDiscretePars(ctstanfitobj = f,subjects = "all",times=seq(from=0,to=6,by=0.05))

ctStanDiscreteParsPlot(x,times=seq(from=0,to=6,by=0.05)) # this works fine
ctStanDiscreteParsPlot(x) # this produce error
```
> Error in set(x, j = name, value = value) : 
> Supplied 303 items to be assigned to 363 items of column 'x'. If you wish to 'recycle' the RHS please use rep() to make this intent clear to readers of your code.

**Comment by cdriveraus** [comment]
Ok. I cleaned up a bunch of the old junk and made it a bit nicer and faster. Can facet by subject, or just plot them one over another. Can also output the data.table and ggplot code to fiddle with it yourself.

![image](https://user-images.githubusercontent.com/4108549/98738465-062ca880-23a8-11eb-8272-7823091caa05.png)

`  
    n <- 30
    dri <- sort(-log1p(exp(rnorm(n,0,2))))
    
    for(i in 1:n){
      gm <- ctModel(LAMBDA=diag(2), DRIFT = c(dri[i]+rnorm(1,0,.2),(dri[i]+1+rnorm(1,0,.3))/10,0,-1),
        DIFFUSION = c(2,2,0,.1),
        MANIFESTVAR = diag(.2,2),Tpoints=30,T0MEANS = 10)
      d <- data.frame(ctGenerate(ctmodelobj = gm,n.subjects = 1,dtmean = .1),dri=dri[i])
      d$id <- i
      if(i==1) dat <- d else dat <- rbind(dat,d)
    }
    plot(dat$time,dat$Y1)
    plot(dat$Y2,dat$Y1)
    
    m <- ctModel(LAMBDA=diag(2),type='stanct',
      DRIFT = c('dr1||||dri','dr12||||dri','dr21','dr22'),
      TIpredNames = 'dri',tipredDefault = F)
    m$pars$indvarying<-FALSE
    
    f=ctStanFit(datalong = dat,ctstanmodel = m,plot=50,cores=1,
      savesubjectmatrices = T,verbose=0)
    
    
    ctStanDiscretePars(f,subjects=1:3,plot=T,nsamples = 50)
    ctStanDiscretePars(f,subjects=1:3,plot=T,nsamples = 50,observational = T)
    ctStanDiscretePars(f,subjects=1:3,plot=T,nsamples = 50,observational = T,cov=T)
    ctStanDiscretePars(f,subjects=5:8,plot=T,nsamples = 50,facets='Subject')
    `

**Comment by Kyabdro** [comment]
Hi, thank you for all this work...

Unfortunately, I've not be able to enjoy all this, I got an error message when using `ctSanDiscretePars`

> Computing temporal regression coefficients for 100 samples, may take a moment...
> Error in sqrt((diag(ctpars$asymDIFFUSION[i, min(j, nsubs$asymDIFFUSION),  : 
> 2 arguments passed to 'sqrt' which requires 1 _(this line is translated from french)_

**Comment by Kyabdro** [comment]
Ok, the problem was that the argument `standardized` was specified, without this parameter (that I understood to be obsolete) this works fine again.

**Comment by Kyabdro** [comment]
Now, I'm getting all individual trajectories instead of the mean of the group of the selected people like the fuction did before.

Here the graph before the update : 

![Image1](https://user-images.githubusercontent.com/43805947/98922862-4177c600-24d3-11eb-9214-f05e90a2d8ab.png)

The new graph : 

![Rplot](https://user-images.githubusercontent.com/43805947/98922977-62401b80-24d3-11eb-91f1-0eef22eebd89.png)

 I'm interested by group means (as in the first graph), and not individual trajectories in the same plot. 

Was it your intention to have individual trajectories plotted by default? If so, that's fine, I think I can manage the data to plot the average myself.

Note also that with my data both `ctSanDiscretePars` and `ctSanDiscretePars` fuctions are long to be claculated. I presume this is due to estimation of all single trajectories... What if I wanted to make the estimation as efficient as with `subjects="all"` but for a reduced set of subjects ?

**Comment by cdriveraus** [comment]
It was my intention yeah, but we've come this far it's easy to throw in the 'splitSubjects' argument which you'll want to set FALSE. Also may want to try out the ggcode=FALSE argument, which will just give you the data.table and plotting code. You'll have to fill in some of the arguments in the plot code that will be 'not found' otherwise.

**Comment by Kyabdro** [comment]
Thanks, this is very clear.

Here is my new graph (using `SplitSubjects=F`) : 

![Rplot2](https://user-images.githubusercontent.com/43805947/98927370-bdc0d800-24d8-11eb-8c15-0585f9a20a62.png)

If I understand well, the only difference now with the first graph of my previous comment is that intervals include all subjects here but 95% previously. Is that right? Is it the right manner to infer significance of an effect for one group if the intervals of that effect for 95% subjects of the group does not include 0 ? So do I have to exclude 5% upper and lower bounds of the graph to get what is plotted for all subject when `subjects='all'` ?

In reality I'm splitting the subjects on the basis of a TI variable that strongly  moderate the Bonheur.Selfless effect that you can see in the graphs. For visual clarity, I wanted to show the upper and lower groups in this TI in the same graph. I was happy to see that intervals did not include 0 in the previous graph, that's the reason of all my questions...


![TI](https://user-images.githubusercontent.com/43805947/98929121-fe215580-24da-11eb-8a99-146c8dac705b.png)

I'm couscious that these questions are not directly related with the package, please tell me if I abuse of your time here...

**Comment by cdriveraus** [comment]
For significance checks, I would look to either a) the intervals of the predictor effect (ie group) on the drift parameters of interest, or b) model comparison to a model without the group difference. The latter can be done crudely using AIC / likelihood values, or likely better using the still somewhat in development ctLOO function. It may be there are research questions where the difference in prediction at a specific time distance (ie a discrete time effect) is of interest, I think this is less common than people seem to think, but would be most appropriately done, *I think*,  by getting the samples returned by ctStanDiscretePars and performing some kind of simple comparison (e.g. t test) between the two groups, just selecting the time point of interest.

**Comment by cdriveraus** [comment]
Also,  'all' is perhaps misleading, and was more appropriate at an earlier incarnation. 'all' uses the population mean drift matrix, and it's distribution, which will be much narrower in general than the overall distribution of subject level drift matrices.

**Comment by Kyabdro** [comment]
Thank you very much for all this coding and information. I think tere is nothing to add, I will now close the issue.

I wish you good luck with the package!
